import numpy as np
ar1 = np.array([1, 2, 3])
print(f&#39;NumPy Array:\n{ar1}&#39;)
a = np.zeros((3, 4))
print(&quot;NumPy Array of zeroes\n&quot;,a)
tuple1 = (43, 21, 32, 67, 21, 5)
print(&quot;Type of tuple: &quot;, type(tuple1))
array = np.asarray(tuple1)
print(&quot;Type of array: &quot;, type(array))
rand = np.random.randint(5,10)
print(&quot;First array\n&quot;, rand)
rand2 = np.random.randint(10,90,(4,5))
print(&quot;Second array\n&quot;,rand2)
